In [3]:
import pandas as pd
import numpy as np
import sklearn
location = 'loansmall.csv'
df = pd.read_csv(location)
df.head(None)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,1077501,1296599,5000,5000,4975.00000,36 months,10.65,162.87,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.00000,60 months,15.27,59.83,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.00000,36 months,15.96,84.33,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.00000,36 months,13.49,339.31,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.00000,60 months,12.69,67.79,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1075269,1311441,5000,5000,5000.00000,36 months,7.90,156.46,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1069639,1304742,7000,7000,7000.00000,60 months,15.96,170.08,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1072053,1288686,3000,3000,3000.00000,36 months,18.64,109.43,E,E1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1071795,1306957,5600,5600,5600.00000,60 months,21.28,152.39,F,F2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1071570,1306721,5375,5375,5350.00000,60 months,12.69,121.45,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1070078,1305201,6500,6500,6500.00000,60 months,14.65,153.45,C,C3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1069908,1305008,12000,12000,12000.00000,36 months,12.69,402.54,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1064687,1298717,9000,9000,9000.00000,36 months,13.49,305.38,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1069866,1304956,3000,3000,3000.00000,36 months,9.91,96.68,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1069057,1303503,10000,10000,10000.00000,36 months,10.65,325.74,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1069759,1304871,1000,1000,1000.00000,36 months,16.29,35.31,D,D1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1065775,1299699,10000,10000,10000.00000,36 months,15.27,347.98,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1069971,1304884,3600,3600,3600.00000,36 months,6.03,109.57,A,A1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1062474,1294539,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1069742,1304855,9200,9200,9200.00000,36 months,6.03,280.01,A,A1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1069740,1284848,20250,20250,19142.16108,60 months,15.27,484.63,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1039153,1269083,21000,21000,21000.00000,36 months,12.42,701.73,B,B4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1069710,1304821,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1069700,1304810,10000,10000,10000.00000,36 months,11.71,330.76,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1069559,1304634,6000,6000,6000.00000,36 months,11.71,198.46,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1069697,1273773,15000,15000,15000.00000,36 months,9.91,483.38,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1069800,1304679,15000,15000,8725.00000,36 months,14.27,514.64,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1069657,1304764,5000,5000,5000.00000,60 months,16.77,123.65,D,D2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1069799,1304678,4000,4000,4000.00000,36 months,11.71,132.31,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1047704,1278806,8500,8500,8500.00000,36 months,11.71,281.15,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194081,1578841,1847814,11100,11100,11100.00000,36 months,17.77,400.02,D,D1,...,NaN,NaN,NaN,NaN,NaN,NaN,27500.0,NaN,NaN,NaN
194082,1578871,1847846,7500,7500,7500.00000,36 months,11.14,246.04,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,11400.0,NaN,NaN,NaN
194083,1578875,1847850,22000,22000,22000.00000,60 months,19.72,579.45,D,D5,...,NaN,NaN,NaN,NaN,NaN,NaN,16600.0,NaN,NaN,NaN
194084,1578850,1847823,10000,10000,10000.00000,60 months,11.14,218.13,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,39000.0,NaN,NaN,NaN
194085,1578201,1846933,4425,4425,4425.00000,36 months,8.90,140.51,A,A5,...,NaN,NaN,NaN,NaN,NaN,NaN,9400.0,NaN,NaN,NaN
194086,1578845,1847818,7300,7300,7300.00000,36 months,7.90,228.42,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,22400.0,NaN,NaN,NaN
194087,1578856,1847830,6250,6250,6250.00000,36 months,10.16,202.14,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,8500.0,NaN,NaN,NaN
194088,1552693,1818874,10000,10000,10000.00000,36 months,12.12,332.72,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,16600.0,NaN,NaN,NaN
194089,1570658,1838259,9250,9250,9250.00000,36 months,15.80,324.29,C,C3,...,NaN,NaN,NaN,NaN,NaN,NaN,8800.0,NaN,NaN,NaN
194090,1564120,1831618,7000,7000,7000.00000,36 months,10.16,226.40,B,B1,...,NaN,NaN,NaN,NaN,NaN,NaN,42500.0,NaN,NaN,NaN
194091,1579023,1847975,14675,14675,14675.00000,36 months,14.09,502.20,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,18079.0,NaN,NaN,NaN
194092,1578763,1847726,12000,12000,12000.00000,36 months,12.12,399.26,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,9100.0,NaN,NaN,NaN
194093,1579018,1847969,5275,5275,5275.00000,36 months,8.90,167.50,A,A5,...,NaN,NaN,NaN,NaN,NaN,NaN,68000.0,NaN,NaN,NaN
194094,1553044,1819231,23500,23500,23500.00000,60 months,20.49,629.04,E,E1,...,NaN,NaN,NaN,NaN,NaN,NaN,18400.0,NaN,NaN,NaN
194095,1579002,1847953,10000,10000,10000.00000,36 months,14.09,342.22,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,21400.0,NaN,NaN,NaN
194096,1477178,1734798,15000,15000,15000.00000,36 months,7.62,467.43,A,A3,...,NaN,NaN,NaN,NaN,NaN,NaN,56800.0,NaN,NaN,NaN
194097,1578784,1847750,4375,4375,4375.00000,36 months,12.12,145.57,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,7300.0,NaN,NaN,NaN
194098,1561362,1828302,20050,20050,20050.00000,36 months,6.62,615.61,A,A2,...,NaN,NaN,NaN,NaN,NaN,NaN,46400.0,NaN,NaN,NaN
194099,1578964,1847710,20000,20000,20000.00000,36 months,7.90,625.81,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,86297.0,NaN,NaN,NaN
194100,1576118,1844945,5000,5000,5000.00000,60 months,15.31,119.77,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,52600.0,NaN,NaN,NaN
194101,1578752,1847715,15350,15350,15350.00000,36 months,14.09,525.30,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,7100.0,NaN,NaN,NaN
194102,1578735,1847500,6000,6000,6000.00000,36 months,16.29,211.81,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,30462.0,NaN,NaN,NaN
194103,1578534,1847676,5500,5500,5500.00000,36 months,12.12,183.00,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,29300.0,NaN,NaN,NaN
194104,1578522,1847663,30000,30000,29750.00000,36 months,18.75,1095.90,D,D3,...,NaN,NaN,NaN,NaN,NaN,NaN,41400.0,NaN,NaN,NaN
194105,1578517,1847658,3400,3400,3400.00000,36 months,6.03,103.49,A,A1,...,NaN,NaN,NaN,NaN,NaN,NaN,10700.0,NaN,NaN,NaN
194106,1578738,1783058,8000,8000,8000.00000,36 months,15.31,278.54,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,15000.0,NaN,NaN,NaN
194107,1572131,1840206,12350,12350,12350.00000,36 months,6.62,379.20,A,A2,...,NaN,NaN,NaN,NaN,NaN,NaN,65000.0,NaN,NaN,NaN
194108,1573779,1841705,19700,19700,19450.00000,36 months,14.09,674.17,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,26700.0,NaN,NaN,NaN
194109,1570647,1838247,15875,15875,15625.00000,36 months,14.09,543.27,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,11400.0,NaN,NaN,NaN
194110,1578497,1847637,12500,12500,12500.00000,36 months,15.80,438.23,C,C3,...,NaN,NaN,NaN,NaN,NaN,NaN,4200.0,NaN,NaN,NaN

df.isnull().sum()

In [4]:
medf = df.loc[df['addr_state'] == 'ME']

In [5]:
medf.head(None)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
39576,176206,176187,3000,3000,750.0,36 months,9.33,95.87,B,B3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39660,142608,74724,5000,5000,2350.0,36 months,10.59,162.73,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39758,109355,109346,1200,1200,0.0,36 months,11.54,39.60,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df1=medf.dropna(axis=1,how='all')
df1.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq
39576,176206,176187,3000,3000,750.0,36 months,9.33,95.87,B,B3,...,0.000000,0.0,0.0,Dec-10,100.22,May-11,0.0,1,INDIVIDUAL,0.0
39660,142608,74724,5000,5000,2350.0,36 months,10.59,162.73,C,C2,...,104.942381,0.0,0.0,Oct-10,490.01,Sep-10,0.0,1,INDIVIDUAL,0.0
39758,109355,109346,1200,1200,0.0,36 months,11.54,39.60,C,C5,...,0.000000,0.0,0.0,Jul-10,39.45,Jul-10,NaN,1,INDIVIDUAL,0.0

In [7]:
grade = pd.pivot_table(medf, values=[ 'loan_amnt', 'int_rate' ], index=['addr_state', 'grade'],
                    aggfunc={'loan_amnt': [len, min, max, np.mean],
                            'int_rate': [min, max, np.mean]})
grade.head(None)

                 int_rate                loan_amnt
                      max    mean    min       len   max  mean   min
addr_state grade
ME         B         9.33   9.330   9.33         1  3000  3000  3000
           C        11.54  11.065  10.59         2  5000  3100  1200

In [8]:
df1.corr()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,...,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,policy_code,acc_now_delinq
id,1.000000,0.650239,0.470839,0.470839,0.309578,-0.996973,0.453781,0.736064,0.022559,NaN,...,0.299265,0.470839,0.367664,-0.002980,NaN,NaN,0.121325,NaN,NaN,NaN
member_id,0.650239,1.000000,-0.364090,-0.364090,-0.521108,-0.707341,-0.381939,0.992888,-0.744867,NaN,...,-0.530317,-0.364090,-0.467448,-0.761664,NaN,NaN,-0.675227,NaN,NaN,NaN
loan_amnt,0.470839,-0.364090,1.000000,1.000000,0.984641,-0.400820,0.999815,-0.250617,0.892616,NaN,...,0.982693,1.000000,0.993538,0.880812,NaN,NaN,0.932827,NaN,NaN,NaN
funded_amnt,0.470839,-0.364090,1.000000,1.000000,0.984641,-0.400820,0.999815,-0.250617,0.892616,NaN,...,0.982693,1.000000,0.993538,0.880812,NaN,NaN,0.932827,NaN,NaN,NaN
funded_amnt_inv,0.309578,-0.521108,0.984641,0.984641,1.000000,-0.234709,0.987817,-0.415789,0.957616,NaN,...,0.999941,0.984641,0.998094,0.949947,NaN,NaN,0.981409,NaN,NaN,NaN
int_rate,-0.996973,-0.707341,-0.400820,-0.400820,-0.234709,1.000000,-0.383122,-0.786467,0.055240,NaN,...,-0.224171,-0.400820,-0.294245,0.080722,NaN,NaN,-0.043781,NaN,NaN,NaN
installment,0.453781,-0.381939,0.999815,0.999815,0.987817,-0.383122,1.000000,-0.269193,0.901123,NaN,...,0.986074,0.999815,0.995537,0.889757,NaN,NaN,0.939585,NaN,NaN,NaN
annual_inc,0.736064,0.992888,-0.250617,-0.250617,-0.415789,-0.786467,-0.269193,1.000000,-0.660134,NaN,...,-0.425611,-0.250617,-0.358876,-0.679102,NaN,NaN,-0.582608,NaN,NaN,NaN
dti,0.022559,-0.744867,0.892616,0.892616,0.957616,0.055240,0.901123,-0.660134,1.000000,NaN,...,0.960678,0.892616,0.938017,0.999674,NaN,NaN,0.995097,NaN,NaN,NaN
delinq_2yrs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
inq_last_6mths,-0.002980,-0.761664,0.880812,0.880812,0.949947,0.080722,0.889757,-0.679102,0.999674,NaN,...,0.953274,0.880812,0.928859,1.000000,NaN,NaN,0.992247,NaN,NaN,NaN
mths_since_last_delinq,-0.864532,-0.180329,-0.850439,-0.850439,-0.745528,0.822839,-0.840162,-0.296150,-0.521954,NaN,...,-0.738269,-0.850439,-0.785234,-0.500000,NaN,NaN,-0.603755,NaN,NaN,NaN
mths_since_last_record,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
open_acc,0.324510,-0.507606,0.987267,0.987267,0.999876,-0.249984,0.990145,-0.401419,0.952962,NaN,...,0.999647,0.987267,0.998942,0.944911,NaN,NaN,0.978266,NaN,NaN,NaN
pub_rec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
revol_bal,0.219623,0.883988,-0.757273,-0.757273,-0.859668,-0.294811,-0.769696,0.822041,-0.970382,NaN,...,-0.865148,-0.757273,-0.826507,-0.976235,NaN,NaN,-0.941732,NaN,NaN,NaN
revol_util,-0.558100,0.267505,-0.994817,-0.994817,-0.961786,0.491895,-0.992677,0.150886,-0.842153,NaN,...,-0.958765,-0.994817,-0.976848,-0.828107,NaN,NaN,-0.891355,NaN,NaN,NaN
total_acc,0.497417,-0.335634,0.999539,0.999539,0.978883,-0.428461,0.998769,-0.221098,0.878512,NaN,...,0.976613,0.999539,0.989632,0.866025,NaN,NaN,0.921452,NaN,NaN,NaN
out_prncp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
out_prncp_inv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_pymnt,0.445969,-0.390008,0.999608,0.999608,0.989140,-0.375028,0.999962,-0.277607,0.904881,NaN,...,0.987491,0.999608,0.996325,0.893715,NaN,NaN,0.942544,NaN,NaN,NaN
total_pymnt_inv,0.299265,-0.530317,0.982693,0.982693,0.999941,-0.224171,0.986074,-0.425611,0.960678,NaN,...,1.000000,0.982693,0.997368,0.953274,NaN,NaN,0.983430,NaN,NaN,NaN
total_rec_prncp,0.470839,-0.364090,1.000000,1.000000,0.984641,-0.400820,0.999815,-0.250617,0.892616,NaN,...,0.982693,1.000000,0.993538,0.880812,NaN,NaN,0.932827,NaN,NaN,NaN
total_rec_int,0.367664,-0.467448,0.993538,0.993538,0.998094,-0.294245,0.995537,-0.358876,0.938017,NaN,...,0.997368,0.993538,1.000000,0.928859,NaN,NaN,0.967696,NaN,NaN,NaN
total_rec_late_fee,-0.002980,-0.761664,0.880812,0.880812,0.949947,0.080722,0.889757,-0.679102,0.999674,NaN,...,0.953274,0.880812,0.928859,1.000000,NaN,NaN,0.992247,NaN,NaN,NaN
recoveries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
collection_recovery_fee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last_pymnt_amnt,0.121325,-0.675227,0.932827,0.932827,0.981409,-0.043781,0.939585,-0.582608,0.995097,NaN,...,0.983430,0.932827,0.967696,0.992247,NaN,NaN,1.000000,NaN,NaN,NaN
collections_12_mths_ex_med,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
policy_code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acc_now_delinq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
import statsmodels.formula.api as sm
result = sm.ols(formula = 'int_rate ~ annual_inc + mths_since_last_delinq + revol_util + loan_amnt + total_acc', data=df1).fit()
result.summary()

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/statsmodels/stats/stattools.py:72: ValueWarning: omni_normtest is not valid with less than 8 observations; 3 samples were given.
  "samples were given." % int(n), ValueWarning)
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1392: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - np.divide(self.nobs - self.k_constant, self.df_resid) * (1 - self.rsquared)
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1392: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - np.divide(self.nobs - self.k_constant, self.df_resid) * (1 - self.rsquared)
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1400: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1353: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               int_rate   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                    nan
Method:                 Least Squares   F-statistic:                     0.000
Date:                Wed, 24 Oct 2018   Prob (F-statistic):                nan
Time:                        22:37:45   Log-Likelihood:                 89.980
No. Observations:                   3   AIC:                            -174.0
Df Residuals:                       0   BIC:                            -176.7
Df Model:                           2
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  0.0010        inf          0        nan         nan         nan
annual_inc             -2.333e-05        inf         -0        nan         nan         nan
mths_since_last_delinq     0.0466        inf          0        nan         nan         nan
revol_util                 0.1089        inf          0        nan         nan         nan
loan_amnt                  0.0022        inf          0        nan         nan         nan
total_acc                  0.0034        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.676
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.317
Skew:                           0.268   Prob(JB):                        0.853
Kurtosis:                       1.500   Cond. No.                         854.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.
"""